name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build, lint, and test on Deno and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Deno
        uses: denoland/setup-deno@v1

      - name: Build
        run: deno task build

      - name: Lint
        run: deno check mod.ts --all --reload

      - name: Test
        run: deno task test
